### ISSUE TITLE
Upgrade  "guzzlehttp/guzzle": "~4.0" to be "~5.0"

### ISSUE THREAD

**Issue by daniel-aranda** [nticaric/awis#1]
Could you please upgrade  "guzzlehttp/guzzle": "~4.0" to be  "guzzlehttp/guzzle": "~5.0"?

I tried to use your library over a running system up to date. Current stable version of guzzle is 5.0 and so I got this error message from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nticaric/awis dev-master -> satisfiable by nticaric/awis[dev-master].
    - nticaric/awis dev-master requires guzzlehttp/guzzle ~4.0 -> no matching package found.

```

**Comment by nticaric** [comment]
I just updated guzzle, can you confirm everything is working fine for you?

**Comment by daniel-aranda** [comment]
It's working. Thank You.
